# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: inference.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'inference.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0finference.proto\"\"\n\x10InferenceRequest\x12\x0e\n\x06prompt\x18\x01 \x01(\t\"V\n\rAudioResponse\x12\r\n\x05\x61udio\x18\x01 \x01(\x0c\x12\x13\n\x0bsample_rate\x18\x02 \x01(\x05\x12!\n\x06status\x18\x03 \x01(\x0e\x32\x11.GenerationStatus\"\x1e\n\x0cImageRequest\x12\x0e\n\x06prompt\x18\x01 \x01(\t\"p\n\rImageResponse\x12\r\n\x05image\x18\x01 \x01(\x0c\x12\r\n\x05width\x18\x02 \x01(\x05\x12\x0e\n\x06height\x18\x03 \x01(\x05\x12\x0e\n\x06\x66ormat\x18\x04 \x01(\t\x12!\n\x06status\x18\x05 \x01(\x0e\x32\x11.GenerationStatus*-\n\x10GenerationStatus\x12\r\n\tGENERATED\x10\x00\x12\n\n\x06\x46\x41ILED\x10\x01\x32u\n\x0fInferenceServer\x12\x32\n\rGenerateAudio\x12\x11.InferenceRequest\x1a\x0e.AudioResponse\x12.\n\rGenerateImage\x12\r.ImageRequest\x1a\x0e.ImageResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'inference_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GENERATIONSTATUS']._serialized_start=289
  _globals['_GENERATIONSTATUS']._serialized_end=334
  _globals['_INFERENCEREQUEST']._serialized_start=19
  _globals['_INFERENCEREQUEST']._serialized_end=53
  _globals['_AUDIORESPONSE']._serialized_start=55
  _globals['_AUDIORESPONSE']._serialized_end=141
  _globals['_IMAGEREQUEST']._serialized_start=143
  _globals['_IMAGEREQUEST']._serialized_end=173
  _globals['_IMAGERESPONSE']._serialized_start=175
  _globals['_IMAGERESPONSE']._serialized_end=287
  _globals['_INFERENCESERVER']._serialized_start=336
  _globals['_INFERENCESERVER']._serialized_end=453
# @@protoc_insertion_point(module_scope)
